# Generated by Django 3.1 on 2020-08-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boast', models.BooleanField()),
                ('post_text', models.CharField(max_length=280)),
                ('up_votes', models.IntegerField()),
                ('down_votes', models.IntegerField()),
                ('submission_date', models.DateTimeField()),
            ],
        ),
    ]
